### ISSUE TITLE
Doesn't work with vue-cli?

### ISSUE THREAD

**Issue by Anima-t3d** [jypblue/vue-ellipsis#2]
I am using nuxt.js to run my vue app with webpack. However I set up the plugin in `nuxt.config.js` and tried to modify the webpack `resolve` config, as well as tried to import the `vue` with compiler. However the error persists and the `ellipsis` component isn't available for me to use in my app. It seems related to the fact the code you wrote uses a template string instead of `.vue`?

Tried setting up webpack based on https://github.com/charliekassel/vuejs-datepicker/issues/32

Currently got it to work by copy and pasting your code and create my own `ellipsis.vue` component in my app.

**Comment by jypblue** [comment]
@Anima-t3d thk i will change my rollup config
