### ISSUE TITLE
TypeError: Cannot set property 'innerHTML' of undefined     at a.handleSubstrSentence

### ISSUE THREAD

**Issue by chanlito** [jypblue/vue-ellipsis#5]
I'm getting this error, can't figure why. Anyone seeing this error as well?

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by jypblue** [comment]
i will check it after china
Spring festival. maybe the dom
 don’t rendered when the function code run
@chanlito 


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
