### ISSUE TITLE
English translation for "Ellipsis Component Attributes"

### ISSUE THREAD

**Issue by scheinercc** [jypblue/vue-ellipsis#6]
https://github.com/jypblue/vue-ellipsis#ellipsis-component-attributes

_(disclaimer: Google translate + my own interpretation)_

**Top Row:** 
- Parameter
- Description
- Type
- Default
- Required

**Descriptions:** 
- Need to add ellipsis 
_(not quite sure what that means? Is it "The data the ellipsis needs to be applied to"?)_
- Number of lines to display
- Single line height (set to the actual single line height, if you use `rem` please calculate the conversion)
_(should that read "please calculate the corresponding `px` value")_
- String at the end of the sentence (e.g. ... ellipsis)
_(Is that what it means? Google translation was quite different.)_
- HTML element at the end of the sentence
- Click callback function

**Comment by jypblue** [comment]
yes, your translation is right, i'll be add later, thanks @scheinercc
